# Generated by Django 3.2.4 on 2021-09-12 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gragh',
            name='data_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='gragh',
            name='x_axis',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gragh',
            name='y_axis',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gragh',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gragh_device', to='dashboard.device'),
        ),
    ]
